server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: true
    # false表示自己端是注册中心，职责是维护服务实例，并不需要检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/