server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从服务注册中心动态创建路由的功能，理由微服务名进行路由
      routes:
        - id: payment_routh # 路由名称，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  # 断言，路径相匹配的进行路由
            - After=2021-08-03T15:17:41.466+08:00[Asia/Shanghai] # 访问路径需要在这个时间之后

        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
#            - Cookie=username,zzyy # 设置带有cook的，键值对  http://localhost:9527/payment/lb --cookie "username=zzyy"
#            - Header=X-Request-Id,\d+ # 请求头要有X-Request-Id属性，并且值为整数的正则表达式，curl http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-id:123"


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
